// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHBnzvy7ZlijdN-sIjg2SpEzL7BbMsnzQ',
    appId: '1:761253690145:web:b55a426f71b7ee2ab9dc60',
    messagingSenderId: '761253690145',
    projectId: 'voice-todo-4666b',
    authDomain: 'voice-todo-4666b.firebaseapp.com',
    storageBucket: 'voice-todo-4666b.firebasestorage.app',
    measurementId: 'G-EZ1JRZ79GX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGjx8WjUWBBkqfTk-Xdq3IwwyyDyYvSGI',
    appId: '1:761253690145:android:fe083668dfb66ce7b9dc60',
    messagingSenderId: '761253690145',
    projectId: 'voice-todo-4666b',
    storageBucket: 'voice-todo-4666b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfZMFy5dNaAZgWbndlWsi6Q-FqfD2M_e8',
    appId: '1:761253690145:ios:eb6f7e0bcea701ffb9dc60',
    messagingSenderId: '761253690145',
    projectId: 'voice-todo-4666b',
    storageBucket: 'voice-todo-4666b.firebasestorage.app',
    iosBundleId: 'com.example.voiceTodo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfZMFy5dNaAZgWbndlWsi6Q-FqfD2M_e8',
    appId: '1:761253690145:ios:eb6f7e0bcea701ffb9dc60',
    messagingSenderId: '761253690145',
    projectId: 'voice-todo-4666b',
    storageBucket: 'voice-todo-4666b.firebasestorage.app',
    iosBundleId: 'com.example.voiceTodo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHBnzvy7ZlijdN-sIjg2SpEzL7BbMsnzQ',
    appId: '1:761253690145:web:319e6935d91f61b5b9dc60',
    messagingSenderId: '761253690145',
    projectId: 'voice-todo-4666b',
    authDomain: 'voice-todo-4666b.firebaseapp.com',
    storageBucket: 'voice-todo-4666b.firebasestorage.app',
    measurementId: 'G-5330BHCNX1',
  );
}
